genome_url: "http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
annotation_url: "http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gtf.gz"

datasets:
#  - "gonzalobenegas/gwas"
#  - "gonzalobenegas/eqtl"
#  - "gonzalobenegas/sqtl"
  #- "gonzalobenegas/dsqtl"
  #- "gonzalobenegas/splicing_assay"
  - "gonzalobenegas/siraj_gwas_highpip"
  - "gonzalobenegas/siraj_eqtl_highpip"
  - "gonzalobenegas/siraj_gwas_highpip_emvar"
  - "gonzalobenegas/siraj_eqtl_highpip_emvar"

features:
  - "GPN-MSA_absLLR"
  - "GPN-MSA_InnerProducts"
#  - "Enformer_absDelta"
#  - Pangolin
#  - CADD

feature_sets:
  GPN-MSA:
    - "GPN-MSA_absLLR"
    - "GPN-MSA_InnerProducts"
  Enformer:
    - "Enformer_absDelta"
  CADD+Enformer:
    - CADD
    - "Enformer_absDelta"
  GPN-MSA+Enformer:
    - "GPN-MSA_absLLR"
    - "GPN-MSA_InnerProducts"
    - "Enformer_absDelta"
  GPN-MSA+Pangolin:
    - "GPN-MSA_absLLR"
    - "GPN-MSA_InnerProducts"
    - "Pangolin"

dataset_eval_models:
  gonzalobenegas/gwas:
    - GPN-MSA.LogisticRegression
    - Enformer.LogisticRegression
    - GPN-MSA+Enformer.LogisticRegression
    #- GPN-MSA_absLLR.Unsupervised
    #- Enformer_absDelta.Unsupervised
    #- CADD.Unsupervised
    #- CADD+Enformer.LogisticRegression
  gonzalobenegas/eqtl:
    - GPN-MSA.LogisticRegression
    - Enformer.LogisticRegression
    - GPN-MSA+Enformer.LogisticRegression
    #- GPN-MSA_absLLR.Unsupervised
    #- Enformer_absDelta.Unsupervised
    #- CADD.Unsupervised
    #- CADD+Enformer.LogisticRegression
  gonzalobenegas/sqtl:
    - GPN-MSA.LogisticRegression
    - Enformer.LogisticRegression
    - GPN-MSA+Enformer.LogisticRegression
    #- GPN-MSA_absLLR.Unsupervised
    #- Enformer_absDelta.Unsupervised
    #- CADD.Unsupervised
    #- CADD+Enformer.LogisticRegression
  gonzalobenegas/dsqtl:
    - GPN-MSA.LogisticRegression.odd_even
    #- Enformer.LogisticRegression.odd_even
    #- GPN-MSA+Enformer.LogisticRegression.odd_even
  gonzalobenegas/siraj_gwas_highpip:
#    - GPN-MSA.LogisticRegression.odd_even
#    - Enformer.LogisticRegression.odd_even
#    - GPN-MSA+Enformer.LogisticRegression.odd_even
    - GPN-MSA.LogisticRegression.chrom
    - Enformer.LogisticRegression.chrom
    - GPN-MSA+Enformer.LogisticRegression.chrom
  gonzalobenegas/siraj_gwas_highpip_emvar:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
#    - GPN-MSA.LogisticRegression.chrom
#    - Enformer.LogisticRegression.chrom
#    - GPN-MSA+Enformer.LogisticRegression.chrom
  gonzalobenegas/siraj_eqtl_highpip:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
  gonzalobenegas/siraj_eqtl_highpip_emvar:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
  gonzalobenegas/splicing_assay:
    - GPN-MSA.LogisticRegression
    - GPN-MSA+Pangolin.LogisticRegression
    - GPN-MSA_absLLR.Unsupervised
    - Pangolin.Unsupervised
    - CADD.Unsupervised

baseline_features:
  gonzalobenegas/gwas:
    - Enformer_absDelta
  gonzalobenegas/eqtl:
    - Enformer_absDelta
  gonzalobenegas/sqtl:
    - Enformer_absDelta
  gonzalobenegas/splicing_assay: []
  gonzalobenegas/dsqtl: []
    #- Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip:
    - Enformer_absDelta
  gonzalobenegas/siraj_eqtl_highpip:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip_emvar:
    - Enformer_absDelta
  gonzalobenegas/siraj_eqtl_highpip_emvar:
    - Enformer_absDelta

gpn_msa:
  model_path: "songlab/gpn-msa-sapiens"
  msa_path: "/accounts/projects/yss/gbenegas/projects/gpn/analysis/human/results/msa/multiz100way/89/all.zarr"
  window_size: 128
