genome_url: "http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
annotation_url: "http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gtf.gz"

clinvar_release: 20240909

datasets:
  - mendelian_traits_matched_9
  - complex_traits_matched_9

consequence_subsets:
  - non_coding_transcript_exon_variant
  - 3_prime_UTR_variant
  - 5_prime_UTR_variant
  - nonexonic_AND_proximal
  - nonexonic_AND_distal

maf_subsets:
#  - maf_0_0.01
#  - maf_0.01_0.05
#  - maf_0.05_0.1
  - maf_0.0_0.1
  - maf_0.1_0.2
  - maf_0.2_0.3
  - maf_0.3_0.4
  - maf_0.4_0.5

features:
#  - GPN-MSA_absLLR
#  - GPN-MSA_InnerProducts
#  - GPN_EmbedDists
#  - Enformer_L2
#  - Borzoi_L2
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_RawScore
  - CADD_Annot
  - Enformer_L2_L2
  - Borzoi_L2_L2

complex_traits_disease:
  - AFib
  - AID_Combined
  - Alzheimer_LTFH
  - Asthma
  - Blood_Clot_Lung
  - BrC
  - CAD
  - CRC
  - Cholelithiasis
  - Depression_GP
  - DVT
  - Fibroblastic_Disorders
  - Glaucoma_Combined
  - Hypothyroidism
  - IBD
  - Inguinal_Hernia
  - Insomnia
  - Migraine_Self
  - PrC
  - T2D
  - T2D_BMI

feature_sets:
  CADD:
    - CADD
  GPN-MSA:
    - GPN-MSA_LLR
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
  NucleotideTransformer:
    - NucleotideTransformer_LLR
    - NucleotideTransformer_absLLR
    - NucleotideTransformer_InnerProducts
  GPN:
    - GPN_LLR
    - GPN_absLLR
    - GPN_InnerProducts
  HyenaDNA:
    - HyenaDNA_LLR
    - HyenaDNA_absLLR
    - HyenaDNA_InnerProducts
  Caduceus:
    - Caduceus_LLR
    - Caduceus_absLLR
    - Caduceus_InnerProducts
  Enformer:
    - Enformer_L2
    - Enformer_L2_L2
  Borzoi:
    - Borzoi_L2
    - Borzoi_L2_L2

  Enformer_L2:
    - Enformer_L2
  Enformer_L2_L2:
    - Enformer_L2_L2

  Borzoi_L2:
    - Borzoi_L2
  Borzoi_L2_L2:
    - Borzoi_L2_L2

  # heavy ensembles
  CADD+GPN-MSA:
    - CADD
    - GPN-MSA_LLR
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts

  CADD+Borzoi:
    - CADD
    - Borzoi_L2
    - Borzoi_L2_L2

  GPN-MSA+Borzoi:
    - GPN-MSA_LLR
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
    - Borzoi_L2
    - Borzoi_L2_L2

  CADD+GPN-MSA+Borzoi:
    - CADD
    - GPN-MSA_LLR
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
    - Borzoi_L2
    - Borzoi_L2_L2

  # light ensembles
  CADD+GPN-MSA_LLR:
    - CADD
    - GPN-MSA_LLR
    - GPN-MSA_absLLR

  CADD+Borzoi_L2_L2:
    - CADD
    - Borzoi_L2_L2

  CADD+GPN-MSA_LLR+Borzoi_L2_L2:
    - CADD
    - GPN-MSA_LLR
    - GPN-MSA_absLLR
    - Borzoi_L2_L2

  GPN_v2_v3_patched_512_17_512_checkpoint_10000:
    - GPN_v2_v3_patched_512_17_512_checkpoint_10000_LLR
    - GPN_v2_v3_patched_512_17_512_checkpoint_10000_absLLR
    - GPN_v2_v3_patched_512_17_512_checkpoint_10000_InnerProducts

  GPN_v2_v3_512_17_512_checkpoint_10000:
    - GPN_v2_v3_512_17_512_checkpoint_10000_LLR
    - GPN_v2_v3_512_17_512_checkpoint_10000_absLLR
    - GPN_v2_v3_512_17_512_checkpoint_10000_InnerProducts

  GPN_v2_all_256_256_512_17_512_checkpoint_10000:
    - GPN_v2_all_256_256_512_17_512_checkpoint_10000_LLR
    - GPN_v2_all_256_256_512_17_512_checkpoint_10000_absLLR
    - GPN_v2_all_256_256_512_17_512_checkpoint_10000_InnerProducts

  GPN_v2_all_256_256_512_17_512_checkpoint_50000:
    - GPN_v2_all_256_256_512_17_512_checkpoint_50000_LLR
    - GPN_v2_all_256_256_512_17_512_checkpoint_50000_absLLR
    - GPN_v2_all_256_256_512_17_512_checkpoint_50000_InnerProducts

  GPN_v2_all_256_256_512_17_512_checkpoint_100000:
    - GPN_v2_all_256_256_512_17_512_checkpoint_100000_LLR
    - GPN_v2_all_256_256_512_17_512_checkpoint_100000_absLLR
    - GPN_v2_all_256_256_512_17_512_checkpoint_100000_InnerProducts

  GPN_v2_all_256_256_512_25_768_checkpoint_10000:
    - GPN_v2_all_256_256_512_25_768_checkpoint_10000_LLR
    - GPN_v2_all_256_256_512_25_768_checkpoint_10000_absLLR
    - GPN_v2_all_256_256_512_25_768_checkpoint_10000_InnerProducts

  GPN_v2_all_256_256_512_25_768_checkpoint_50000:
    - GPN_v2_all_256_256_512_25_768_checkpoint_50000_LLR
    - GPN_v2_all_256_256_512_25_768_checkpoint_50000_absLLR
    - GPN_v2_all_256_256_512_25_768_checkpoint_50000_InnerProducts

  GPN_v2_all_256_256_512_25_768_checkpoint_100000:
    - GPN_v2_all_256_256_512_25_768_checkpoint_100000_LLR
    - GPN_v2_all_256_256_512_25_768_checkpoint_100000_absLLR
    - GPN_v2_all_256_256_512_25_768_checkpoint_100000_InnerProducts

  GPN_v2_bytenet_v4_512_16_256_checkpoint_10000:
    - GPN_v2_bytenet_v4_512_16_256_checkpoint_10000_LLR
    - GPN_v2_bytenet_v4_512_16_256_checkpoint_10000_absLLR
    - GPN_v2_bytenet_v4_512_16_256_checkpoint_10000_InnerProducts
  GPN_v2_bytenet_v5_512_16_256_checkpoint_10000:
    - GPN_v2_bytenet_v5_512_16_256_checkpoint_10000_LLR
    - GPN_v2_bytenet_v5_512_16_256_checkpoint_10000_absLLR
    - GPN_v2_bytenet_v5_512_16_256_checkpoint_10000_InnerProducts
  GPN_v2_bytenet_v6_512_16_256_checkpoint_10000:
    - GPN_v2_bytenet_v6_512_16_256_checkpoint_10000_LLR
    - GPN_v2_bytenet_v6_512_16_256_checkpoint_10000_absLLR
    - GPN_v2_bytenet_v6_512_16_256_checkpoint_10000_InnerProducts
  GPN_v2_bytenet_v7_512_16_256_checkpoint_10000:
    - GPN_v2_bytenet_v7_512_16_256_checkpoint_10000_LLR
    - GPN_v2_bytenet_v7_512_16_256_checkpoint_10000_absLLR
    - GPN_v2_bytenet_v7_512_16_256_checkpoint_10000_InnerProducts
  GPN_v2_bytenet_v8_512_16_256_checkpoint_10000:
    - GPN_v2_bytenet_v8_512_16_256_checkpoint_10000_LLR
    - GPN_v2_bytenet_v8_512_16_256_checkpoint_10000_absLLR
    - GPN_v2_bytenet_v8_512_16_256_checkpoint_10000_InnerProducts

  GPN_v2_bytenet_v6_256_16_256_checkpoint_10000:
    - GPN_v2_bytenet_v6_256_16_256_checkpoint_10000_LLR
    - GPN_v2_bytenet_v6_256_16_256_checkpoint_10000_absLLR
    - GPN_v2_bytenet_v6_256_16_256_checkpoint_10000_InnerProducts

  GPN_v4_v6_512_16_256_checkpoint_10000:
    - GPN_v4_v6_512_16_256_checkpoint_10000_LLR
    - GPN_v4_v6_512_16_256_checkpoint_10000_absLLR
    - GPN_v4_v6_512_16_256_checkpoint_10000_InnerProducts
  GPN_v4_v6_512_16_256_checkpoint_20000:
    - GPN_v4_v6_512_16_256_checkpoint_20000_LLR
    - GPN_v4_v6_512_16_256_checkpoint_20000_absLLR
    - GPN_v4_v6_512_16_256_checkpoint_20000_InnerProducts
  GPN_v4_v6_512_16_256_checkpoint_30000:
    - GPN_v4_v6_512_16_256_checkpoint_30000_LLR
    - GPN_v4_v6_512_16_256_checkpoint_30000_absLLR
    - GPN_v4_v6_512_16_256_checkpoint_30000_InnerProducts

  GPN_v4_v6_512_32_512_checkpoint_10000:
    - GPN_v4_v6_512_32_512_checkpoint_10000_LLR
    - GPN_v4_v6_512_32_512_checkpoint_10000_absLLR
    - GPN_v4_v6_512_32_512_checkpoint_10000_InnerProducts
  GPN_v4_v6_512_64_1024_checkpoint_10000:
    - GPN_v4_v6_512_64_1024_checkpoint_10000_LLR
    - GPN_v4_v6_512_64_1024_checkpoint_10000_absLLR
    - GPN_v4_v6_512_64_1024_checkpoint_10000_InnerProducts
  GPN_v4_v6_512_64_1024_checkpoint_50000:
    - GPN_v4_v6_512_64_1024_checkpoint_50000_LLR
    - GPN_v4_v6_512_64_1024_checkpoint_50000_absLLR
    - GPN_v4_v6_512_64_1024_checkpoint_50000_InnerProducts
  GPN_v4_v6_512_64_1024_checkpoint_100000:
    - GPN_v4_v6_512_64_1024_checkpoint_100000_LLR
    - GPN_v4_v6_512_64_1024_checkpoint_100000_absLLR
    - GPN_v4_v6_512_64_1024_checkpoint_100000_InnerProducts
  GPN_v4_v6_512_64_1024_checkpoint_150000:
    - GPN_v4_v6_512_64_1024_checkpoint_150000_LLR
    - GPN_v4_v6_512_64_1024_checkpoint_150000_absLLR
    - GPN_v4_v6_512_64_1024_checkpoint_150000_InnerProducts

gpn_msa:
  model_path: "songlab/gpn-msa-sapiens"
  msa_path: "/accounts/projects/yss/gbenegas/projects/gpn/analysis/human/results/msa/multiz100way/89/all.zarr"
  window_size: 128

gpn:
  #model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/512/512/512_17_512/checkpoint-100000
  model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_25_768/checkpoint-100000
  window_size: 512
  per_device_batch_size: 2048
  v2_all_256_256_512_17_512_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_17_512/checkpoint-10000
  v2_all_256_256_512_17_512_checkpoint_20000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_17_512/checkpoint-20000
  v2_all_256_256_512_17_512_checkpoint_30000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_17_512/checkpoint-30000
  v2_all_256_256_512_17_512_checkpoint_50000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_17_512/checkpoint-50000
  v2_all_256_256_512_17_512_checkpoint_100000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_17_512/checkpoint-100000

  v2_v3_patched_512_17_512_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_v3/512_17_512/checkpoint-10000

  v2_v3_512_17_512_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_v3/512_17_512/checkpoint-10000
  v2_v3_512_17_512_checkpoint_20000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_v3/512_17_512/checkpoint-20000
  v2_v3_512_17_512_checkpoint_30000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_v3/512_17_512/checkpoint-30000

  v2_all_256_256_512_25_768_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_25_768/checkpoint-10000
  v2_all_256_256_512_25_768_checkpoint_50000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_25_768/checkpoint-50000
  v2_all_256_256_512_25_768_checkpoint_100000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_25_768/checkpoint-100000

  v2_bytenet_v4_512_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_bytenet_v4/512_16_256/checkpoint-10000
  v2_bytenet_v5_512_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_bytenet_v5/512_16_256/checkpoint-10000
  v2_bytenet_v6_512_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_bytenet_v6/512_16_256/checkpoint-10000
  v2_bytenet_v7_512_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_bytenet_v7/512_16_256/checkpoint-10000
  v2_bytenet_v8_512_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_bytenet_v8/512_16_256/checkpoint-10000

  v2_bytenet_v6_256_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_bytenet_v6/256_16_256/checkpoint-10000

  v4_v6_512_16_256_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_16_256/checkpoint-10000
  v4_v6_512_16_256_checkpoint_20000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_16_256/checkpoint-20000
  v4_v6_512_16_256_checkpoint_30000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_16_256/checkpoint-30000

  v4_v6_512_32_512_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_32_512/checkpoint-10000
  v4_v6_512_64_1024_checkpoint_10000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_64_1024/checkpoint-10000
  v4_v6_512_64_1024_checkpoint_50000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_64_1024/checkpoint-50000
  v4_v6_512_64_1024_checkpoint_100000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_64_1024/checkpoint-100000
  v4_v6_512_64_1024_checkpoint_150000:
    model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v4_v6/512_64_1024/checkpoint-150000

cadd:
  url: https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh38/whole_genome_SNVs_inclAnno.tsv.gz
  features:
#  - Type
#  - Length
#  - Consequence
  - GC
  - CpG
  - motifECount
  - motifEHIPos
  - motifEScoreChng
#  - oAA
#  - nAA
  - cDNApos
  - relcDNApos
  - CDSpos
  - relCDSpos
  - protPos
  - relProtPos
#  - Domain
  - Dst2Splice
#  - Dst2SplType
  - minDistTSS
  - minDistTSE
#  - SIFTcat
  - SIFTval
#  - PolyPhenCat
  - PolyPhenVal
  - priPhCons
  - mamPhCons
  - verPhCons
  - priPhyloP
  - mamPhyloP
  - verPhyloP
  - bStatistic
  - targetScan
  - mirSVR-Score
  - mirSVR-E
  - mirSVR-Aln
  - cHmm_E1
  - cHmm_E2
  - cHmm_E3
  - cHmm_E4
  - cHmm_E5
  - cHmm_E6
  - cHmm_E7
  - cHmm_E8
  - cHmm_E9
  - cHmm_E10
  - cHmm_E11
  - cHmm_E12
  - cHmm_E13
  - cHmm_E14
  - cHmm_E15
  - cHmm_E16
  - cHmm_E17
  - cHmm_E18
  - cHmm_E19
  - cHmm_E20
  - cHmm_E21
  - cHmm_E22
  - cHmm_E23
  - cHmm_E24
  - cHmm_E25
  - GerpRS
  - GerpRSpval
  - GerpN
  - GerpS
  - tOverlapMotifs
  - motifDist
  - EncodeH3K4me1-sum
  - EncodeH3K4me1-max
  - EncodeH3K4me2-sum
  - EncodeH3K4me2-max
  - EncodeH3K4me3-sum
  - EncodeH3K4me3-max
  - EncodeH3K9ac-sum
  - EncodeH3K9ac-max
  - EncodeH3K9me3-sum
  - EncodeH3K9me3-max
  - EncodeH3K27ac-sum
  - EncodeH3K27ac-max
  - EncodeH3K27me3-sum
  - EncodeH3K27me3-max
  - EncodeH3K36me3-sum
  - EncodeH3K36me3-max
  - EncodeH3K79me2-sum
  - EncodeH3K79me2-max
  - EncodeH4K20me1-sum
  - EncodeH4K20me1-max
  - EncodeH2AFZ-sum
  - EncodeH2AFZ-max
  - EncodeDNase-sum
  - EncodeDNase-max
  - EncodetotalRNA-sum
  - EncodetotalRNA-max
  - Grantham
  - SpliceAI-acc-gain
  - SpliceAI-acc-loss
  - SpliceAI-don-gain
  - SpliceAI-don-loss
  - MMSp_acceptorIntron
  - MMSp_acceptor
  - MMSp_exon
  - MMSp_donor
  - MMSp_donorIntron
  - Dist2Mutation
  - Freq100bp
  - Rare100bp
  - Sngl100bp
  - Freq1000bp
  - Rare1000bp
  - Sngl1000bp
  - Freq10000bp
  - Rare10000bp
  - Sngl10000bp
#  - EnsembleRegulatoryFeature
  - dbscSNV-ada_score
  - dbscSNV-rf_score
  - RemapOverlapTF
  - RemapOverlapCL
  - EsmScoreMissense
  - EsmScoreInFrame
  - EsmScoreFrameshift
  - RegSeq0
  - RegSeq1
  - RegSeq2
  - RegSeq3
  - RegSeq4
  - RegSeq5
  - RegSeq6
  - RegSeq7
  - Aparent2
  - ZooPriPhyloP
  - ZooVerPhyloP
  - ZooRoCC
  - ZooUCE
#  - Roulette-FILTER
  - Roulette-MR
  - Roulette-AR
  - RawScore
#  - PHRED

nucleotide_transformer:
  model_path: InstaDeepAI/nucleotide-transformer-2.5b-multi-species

hyenadna:
  #model_path: LongSafari/hyenadna-tiny-1k-seqlen-hf
  #model_path: LongSafari/hyenadna-large-1m-seqlen-hf
  model_path: LongSafari/hyenadna-medium-160k-seqlen-hf

caduceus:
  model_path: kuleshov-group/caduceus-ps_seqlen-131k_d_model-256_n_layer-16
  window_size: 131071  # 1 token reserved for the [SEP] at the end
  per_device_batch_size: 32