genome_url: "http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
annotation_url: "http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gtf.gz"

datasets:
#  - "gonzalobenegas/gwas"
#  - "gonzalobenegas/eqtl"
#  - "gonzalobenegas/sqtl"
#  - "gonzalobenegas/splicing_assay"
#  - "gonzalobenegas/dsqtl"
  - "gonzalobenegas/siraj_gwas_highpip"
#  - "gonzalobenegas/siraj_eqtl_highpip"
#  - "gonzalobenegas/siraj_gwas_highpip_emvar"
#  - "gonzalobenegas/siraj_eqtl_highpip_emvar"

features:
#  - "GPN-MSA_absLLR"
#  - "GPN-MSA_InnerProducts"
#  - GPN_EmbedDists
#  - "Enformer_absDelta"
#  - Pangolin
#  - CADD
#  - "Enformer_absDelta_s_het"
#  - s_het
  - Enformer_L2

feature_sets:
  GPN:
    - "GPN_EmbedDists"
  GPN-MSA:
    - "GPN-MSA_absLLR"
    - "GPN-MSA_InnerProducts"
  Enformer:
    - "Enformer_absDelta"
  Enformer+s_het:
    - "Enformer_absDelta"
    - "s_het"
  CADD+Enformer:
    - CADD
    - "Enformer_absDelta"
  GPN-MSA+Enformer:
    - "GPN-MSA_absLLR"
    - "GPN-MSA_InnerProducts"
    - "Enformer_absDelta"
  GPN-MSA+Pangolin:
    - "GPN-MSA_absLLR"
    - "GPN-MSA_InnerProducts"
    - "Pangolin"

dataset_eval_models:
#  gonzalobenegas/gwas:
#    - GPN-MSA.LogisticRegression
#    - Enformer.LogisticRegression
#    - GPN-MSA+Enformer.LogisticRegression
#    #- GPN-MSA_absLLR.Unsupervised
#    #- Enformer_absDelta.Unsupervised
#    #- CADD.Unsupervised
#    #- CADD+Enformer.LogisticRegression
#  gonzalobenegas/eqtl:
#    - GPN-MSA.LogisticRegression
#    - Enformer.LogisticRegression
#    - GPN-MSA+Enformer.LogisticRegression
#    #- GPN-MSA_absLLR.Unsupervised
#    #- Enformer_absDelta.Unsupervised
#    #- CADD.Unsupervised
#    #- CADD+Enformer.LogisticRegression
#  gonzalobenegas/sqtl:
#    - GPN-MSA.LogisticRegression
#    - Enformer.LogisticRegression
#    - GPN-MSA+Enformer.LogisticRegression
#    #- GPN-MSA_absLLR.Unsupervised
#    #- Enformer_absDelta.Unsupervised
#    #- CADD.Unsupervised
#    #- CADD+Enformer.LogisticRegression
  gonzalobenegas/dsqtl:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
    - GPN.LogisticRegression.odd_even
    - Enformer_absDelta.Unsupervised
  gonzalobenegas/siraj_gwas_highpip:
#    - GPN-MSA.LogisticRegression.odd_even
#    - Enformer.LogisticRegression.odd_even
#    - GPN-MSA+Enformer.LogisticRegression.odd_even
#    - GPN-MSA.LogisticRegression.chrom
#    - Enformer.LogisticRegression.chrom
#    - GPN-MSA+Enformer.LogisticRegression.chrom
    #- GPN-MSA+Enformer.RandomForest.chrom
    #- GPN.LogisticRegression.chrom
#    - emVar.Unsupervised
    - Enformer_absDelta.Unsupervised
    - Enformer_L2.Unsupervised
#    - Enformer_absDelta_s_het.Unsupervised
#    - Enformer+s_het.LogisticRegression.chrom
  gonzalobenegas/siraj_eqtl_highpip:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
    #- GPN-MSA+Enformer.RandomForest.odd_even
    #- GPN.LogisticRegression.odd_even
    #- emVar.Unsupervised
    #- Enformer_absDelta.Unsupervised
  #gonzalobenegas/siraj_gwas_highpip_emvar:
  #  - GPN-MSA.LogisticRegression.odd_even
  #  - Enformer.LogisticRegression.odd_even
  #  - GPN-MSA+Enformer.LogisticRegression.odd_even
  #  - GPN.LogisticRegression.odd_even
# #   - GPN-MSA.LogisticRegression.chrom
# #   - Enformer.LogisticRegression.chrom
# #   - GPN-MSA+Enformer.LogisticRegression.chrom
  #gonzalobenegas/siraj_eqtl_highpip_emvar:
  #  - GPN-MSA.LogisticRegression.odd_even
  #  - Enformer.LogisticRegression.odd_even
  #  - GPN-MSA+Enformer.LogisticRegression.odd_even
  #  - GPN.LogisticRegression.odd_even
  ##gonzalobenegas/splicing_assay:
  ##  - GPN-MSA.LogisticRegression
  ##  - GPN-MSA+Pangolin.LogisticRegression
  ##  - GPN-MSA_absLLR.Unsupervised
  ##  - Pangolin.Unsupervised
  ##  - CADD.Unsupervised

baseline_features:
  gonzalobenegas/gwas:
    - Enformer_absDelta
  gonzalobenegas/eqtl:
    - Enformer_absDelta
  gonzalobenegas/sqtl:
    - Enformer_absDelta
  gonzalobenegas/splicing_assay: []
  gonzalobenegas/dsqtl:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip:
    - Enformer_absDelta
    - Enformer_L2
  gonzalobenegas/siraj_eqtl_highpip:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip_emvar:
    - Enformer_absDelta
  gonzalobenegas/siraj_eqtl_highpip_emvar:
    - Enformer_absDelta

gpn_msa:
  model_path: "songlab/gpn-msa-sapiens"
  msa_path: "/accounts/projects/yss/gbenegas/projects/gpn/analysis/human/results/msa/multiz100way/89/all.zarr"
  window_size: 128

gpn:
  model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/512/512/512_17_512/checkpoint-100000
  window_size: 512