genome_url: "http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
annotation_url: "http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gtf.gz"

datasets:
#  - gwas_matched_9
#  - eqtl_matched_1
  - omim_subsampled_99

subsets:
  - all

  - nonexonic
  - missense_variant
  - non_coding_transcript_exon_variant
  - 3_prime_UTR_variant
  - 5_prime_UTR_variant

#  - Height
#  - MCV
#  - MCH
#  - Mono
#  - Plt
#  - eBMD
#  - HbA1c
#  - RBC
#  - ALP
#  - IGF1
#  - HDLC
#  - Eosino
#  - LDLC
#  - SHBG
#  - AG
#  - Lym
#  - Hb
#  - GGT
#  - eGFRcys
#  - ApoA
#  - WBC
#  - eGFR
#  - TP

  - Thyroid
  - Whole_Blood
  - Lung
  - Brain_Cortex
  - Liver

features:
#  - GPN-MSA_absLLR
#  - GPN-MSA_InnerProducts
#  - GPN_EmbedDists
#  - Enformer_L2
#  - Borzoi_L2
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_RawScore
  - CADD_Annot
  - Enformer_L2_L2
  - Borzoi_L2_L2

feature_sets:
  Baseline:
  - minus_MAF
  - minus_TSS_dist
  CADD:
  - CADD
#    - CADD_Annot
#    - minus_MAF
#    - minus_TSS_dist
  Enformer:
    - Enformer_L2_L2
    - minus_MAF
    - minus_TSS_dist
  Borzoi:
    - Borzoi_L2_L2
    - minus_MAF
    - minus_TSS_dist
  GPN-MSA:
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
  GPN-MSA_InnerProducts:
    - GPN-MSA_InnerProducts
  CADD+GPN-MSA_LLR:
    - CADD
    - GPN-MSA_LLR
  phyloP-100v:
    - phyloP-100v
    - minus_MAF
    - minus_TSS_dist
  phastCons-100v:
    - phastCons-100v
    - minus_MAF
    - minus_TSS_dist
  phyloP-241m:
    - phyloP-241m
    - minus_MAF
    - minus_TSS_dist
#  Enformer_precomputed:
#    - Enformer_absDelta
#    - minus_MAF
#    - minus_TSS_dist
  Enformer_L2:
    - Enformer_L2
  Borzoi_L2:
    - Borzoi_L2
  Enformer_L2_L2:
    - Enformer_L2_L2
  Borzoi_L2_L2:
    - Borzoi_L2_L2

  Borzoi_L2+GPN-MSA:
    - Borzoi_L2
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts

  Borzoi_L2+CADD:
    - Borzoi_L2
    - CADD

  CADD+GPN-MSA:
    - CADD
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts

  Borzoi_L2+GPN-MSA+CADD:
    - Borzoi_L2
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
    - CADD

  Enformer_L2+GPN-MSA+CADD:
    - Enformer_L2
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
    - CADD

  Borzoi_L2+Enformer_L2+GPN-MSA+CADD:
    - Borzoi_L2
    - Enformer_L2
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
    - CADD


  Ensemble:
  - CADD
  - Borzoi_L2
  - GPN-MSA_absLLR
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  Ensemble_precomputed:
  - GPN-MSA_absLLR
  - GPN-MSA_InnerProducts
  - Enformer_absDelta
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_Annot

dataset_eval_models:
  gonzalobenegas/siraj_gwas_highpip:
    - Baseline.RandomForest.chrom

    - Ensemble.RandomForest.chrom
    #- Ensemble.XGBoost.chrom

    - CADD.RandomForest.chrom
    - Enformer.RandomForest.chrom
    - Borzoi.RandomForest.chrom
    - GPN-MSA.RandomForest.chrom
    - phyloP-100v.RandomForest.chrom
    - phastCons-100v.RandomForest.chrom
    - phyloP-241m.RandomForest.chrom
  gonzalobenegas/siraj_eqtl_highpip:
    - Baseline.LogisticRegression.odd_even

    - Ensemble_precomputed.LogisticRegression.odd_even

    - GPN-MSA.LogisticRegression.odd_even
    - CADD.LogisticRegression.odd_even
    - Enformer_precomputed.LogisticRegression.odd_even
  gonzalobenegas/dsqtl:
    - Baseline.LogisticRegression.odd_even

    - Ensemble_precomputed.LogisticRegression.odd_even

    - GPN-MSA.LogisticRegression.odd_even
    - CADD.LogisticRegression.odd_even
    - Enformer_precomputed.LogisticRegression.odd_even
  gwas_gokcen_experiment1_Height:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
  gwas_gokcen_experiment1_BMD-HT:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom

  gwas_gokcen_merged_nonexonic_matched:
    - Enformer_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom

  gwas_gokcen_merged_cre_matched:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_Height_cre_matched:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_IBD_cre_matched:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_BMD-HT_cre_matched:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom

  gwas_gokcen_merged_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_Height_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_IBD_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_BMD-HT_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_CD_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_PLT_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_TG_cre_matched_9:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+CADD.LogisticRegression.chrom
    - CADD+GPN-MSA.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom

  gwas_gokcen_BMI_matched_9_nonexonic:
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_AD_matched_9_nonexonic:
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_AD_matched_99_nonexonic:
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
  gwas_gokcen_Intel_matched_9_nonexonic:
    - Borzoi_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom

  gwas_gokcen_merged_matched_1_nonexonic:
    - Borzoi_L2.LogisticRegression.chrom
    - Enformer_L2.LogisticRegression.chrom
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.LogisticRegression.chrom
    - Borzoi_L2+GPN-MSA+CADD.RandomForest.chrom

  gwas_matched_1:
    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom

baseline_features:
  gonzalobenegas/dsqtl:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip: []
  gonzalobenegas/siraj_eqtl_highpip:
    - Enformer_absDelta

gpn_msa:
  model_path: "songlab/gpn-msa-sapiens"
  msa_path: "/accounts/projects/yss/gbenegas/projects/gpn/analysis/human/results/msa/multiz100way/89/all.zarr"
  window_size: 128

gpn:
  #model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/512/512/512_17_512/checkpoint-100000
  model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/256/256/512_25_768/checkpoint-100000
  window_size: 512

cadd:
  url: https://krishna.gs.washington.edu/download/CADD/v1.7/GRCh38/whole_genome_SNVs_inclAnno.tsv.gz
  features:
#  - Type
#  - Length
#  - Consequence
  - GC
  - CpG
  - motifECount
  - motifEHIPos
  - motifEScoreChng
#  - oAA
#  - nAA
  - cDNApos
  - relcDNApos
  - CDSpos
  - relCDSpos
  - protPos
  - relProtPos
#  - Domain
  - Dst2Splice
#  - Dst2SplType
  - minDistTSS
  - minDistTSE
#  - SIFTcat
  - SIFTval
#  - PolyPhenCat
  - PolyPhenVal
  - priPhCons
  - mamPhCons
  - verPhCons
  - priPhyloP
  - mamPhyloP
  - verPhyloP
  - bStatistic
  - targetScan
  - mirSVR-Score
  - mirSVR-E
  - mirSVR-Aln
  - cHmm_E1
  - cHmm_E2
  - cHmm_E3
  - cHmm_E4
  - cHmm_E5
  - cHmm_E6
  - cHmm_E7
  - cHmm_E8
  - cHmm_E9
  - cHmm_E10
  - cHmm_E11
  - cHmm_E12
  - cHmm_E13
  - cHmm_E14
  - cHmm_E15
  - cHmm_E16
  - cHmm_E17
  - cHmm_E18
  - cHmm_E19
  - cHmm_E20
  - cHmm_E21
  - cHmm_E22
  - cHmm_E23
  - cHmm_E24
  - cHmm_E25
  - GerpRS
  - GerpRSpval
  - GerpN
  - GerpS
  - tOverlapMotifs
  - motifDist
  - EncodeH3K4me1-sum
  - EncodeH3K4me1-max
  - EncodeH3K4me2-sum
  - EncodeH3K4me2-max
  - EncodeH3K4me3-sum
  - EncodeH3K4me3-max
  - EncodeH3K9ac-sum
  - EncodeH3K9ac-max
  - EncodeH3K9me3-sum
  - EncodeH3K9me3-max
  - EncodeH3K27ac-sum
  - EncodeH3K27ac-max
  - EncodeH3K27me3-sum
  - EncodeH3K27me3-max
  - EncodeH3K36me3-sum
  - EncodeH3K36me3-max
  - EncodeH3K79me2-sum
  - EncodeH3K79me2-max
  - EncodeH4K20me1-sum
  - EncodeH4K20me1-max
  - EncodeH2AFZ-sum
  - EncodeH2AFZ-max
  - EncodeDNase-sum
  - EncodeDNase-max
  - EncodetotalRNA-sum
  - EncodetotalRNA-max
  - Grantham
  - SpliceAI-acc-gain
  - SpliceAI-acc-loss
  - SpliceAI-don-gain
  - SpliceAI-don-loss
  - MMSp_acceptorIntron
  - MMSp_acceptor
  - MMSp_exon
  - MMSp_donor
  - MMSp_donorIntron
  - Dist2Mutation
  - Freq100bp
  - Rare100bp
  - Sngl100bp
  - Freq1000bp
  - Rare1000bp
  - Sngl1000bp
  - Freq10000bp
  - Rare10000bp
  - Sngl10000bp
#  - EnsembleRegulatoryFeature
  - dbscSNV-ada_score
  - dbscSNV-rf_score
  - RemapOverlapTF
  - RemapOverlapCL
  - EsmScoreMissense
  - EsmScoreInFrame
  - EsmScoreFrameshift
  - RegSeq0
  - RegSeq1
  - RegSeq2
  - RegSeq3
  - RegSeq4
  - RegSeq5
  - RegSeq6
  - RegSeq7
  - Aparent2
  - ZooPriPhyloP
  - ZooVerPhyloP
  - ZooRoCC
  - ZooUCE
#  - Roulette-FILTER
  - Roulette-MR
  - Roulette-AR
  - RawScore
#  - PHRED