genome_url: "http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
annotation_url: "http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gtf.gz"

datasets:
#  - "gonzalobenegas/gwas"
#  - "gonzalobenegas/eqtl"
#  - "gonzalobenegas/sqtl"
#  - "gonzalobenegas/splicing_assay"
#  - "gonzalobenegas/dsqtl"
  - "gonzalobenegas/siraj_gwas_highpip"
#  - "gonzalobenegas/siraj_eqtl_highpip"
#  - "gonzalobenegas/siraj_gwas_highpip_emvar"
#  - "gonzalobenegas/siraj_eqtl_highpip_emvar"

features:
#  - GPN-MSA_absLLR
#  - GPN-MSA_InnerProducts
#  - GPN_EmbedDists
  - Enformer_L2
  - Borzoi_L2
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_RawScore
  - CADD_Annot

feature_sets:
  Baseline:
  - minus_MAF
  - minus_TSS_dist
  GPN:
    - GPN_EmbedDists
  GPN-MSA:
    - GPN-MSA_absLLR
    - GPN-MSA_InnerProducts
    - minus_MAF
    - minus_TSS_dist
  CADD:
    - CADD_Annot
    - minus_MAF
    - minus_TSS_dist
  Enformer:
    - Enformer_L2
    - minus_MAF
    - minus_TSS_dist
  Borzoi:
    - Borzoi_L2
    - minus_MAF
    - minus_TSS_dist
  phyloP-100v:
    - phyloP-100v
    - minus_MAF
    - minus_TSS_dist
  phastCons-100v:
    - phastCons-100v
    - minus_MAF
    - minus_TSS_dist
  phyloP-241m:
    - phyloP-241m
    - minus_MAF
    - minus_TSS_dist
  Ensemble:
  - GPN-MSA_absLLR
  - GPN-MSA_InnerProducts
#  - GPN_EmbedDists
#  - Enformer_L2
  - Borzoi_L2
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_Annot

dataset_eval_models:
  gonzalobenegas/dsqtl:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
    - GPN.LogisticRegression.odd_even
    - Enformer_absDelta.Unsupervised
  gonzalobenegas/siraj_gwas_highpip:
    - Baseline.LogisticRegression.chrom

    - Ensemble.LogisticRegression.chrom

    - GPN-MSA.LogisticRegression.chrom
    - CADD.LogisticRegression.chrom
    - Enformer.LogisticRegression.chrom
    - Borzoi.LogisticRegression.chrom
    - phyloP-100v.LogisticRegression.chrom
    - phastCons-100v.LogisticRegression.chrom
    - phyloP-241m.LogisticRegression.chrom
  gonzalobenegas/siraj_eqtl_highpip:
    - GPN-MSA.LogisticRegression.odd_even
    - Enformer.LogisticRegression.odd_even
    - GPN-MSA+Enformer.LogisticRegression.odd_even
    #- GPN-MSA+Enformer.RandomForest.odd_even
    #- GPN.LogisticRegression.odd_even
    #- emVar.Unsupervised
    #- Enformer_absDelta.Unsupervised

baseline_features:
  gonzalobenegas/gwas:
    - Enformer_absDelta
  gonzalobenegas/eqtl:
    - Enformer_absDelta
  gonzalobenegas/sqtl:
    - Enformer_absDelta
  gonzalobenegas/splicing_assay: []
  gonzalobenegas/dsqtl:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip: []
  gonzalobenegas/siraj_eqtl_highpip:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip_emvar:
    - Enformer_absDelta
  gonzalobenegas/siraj_eqtl_highpip_emvar:
    - Enformer_absDelta

gpn_msa:
  model_path: "songlab/gpn-msa-sapiens"
  msa_path: "/accounts/projects/yss/gbenegas/projects/gpn/analysis/human/results/msa/multiz100way/89/all.zarr"
  window_size: 128

gpn:
  model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/512/512/512_17_512/checkpoint-100000
  window_size: 512