genome_url: "http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
annotation_url: "http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.chr.gtf.gz"

datasets:
#  - "gonzalobenegas/dsqtl"
#  - "gonzalobenegas/siraj_gwas_highpip"
#  - "gonzalobenegas/siraj_eqtl_highpip"

#  - gwas_gokcen_experiment1_IBD
#  - gwas_gokcen_experiment1_Height
#  - gwas_gokcen_experiment1_CD
#  - gwas_gokcen_experiment1_BMD-HT
#  - gwas_gokcen_experiment1_PLT

  - gwas_gokcen_merged_cre_matched

features:
#  - GPN-MSA_absLLR
#  - GPN-MSA_InnerProducts
#  - GPN_EmbedDists
#  - Enformer_L2
#  - Borzoi_L2
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_RawScore
  - CADD_Annot
  - Enformer_L2_L2
  - Borzoi_L2_L2

feature_sets:
  Baseline:
  - minus_MAF
  - minus_TSS_dist
  CADD:
    - CADD_Annot
    - minus_MAF
    - minus_TSS_dist
  Enformer:
    - Enformer_L2_L2
    - minus_MAF
    - minus_TSS_dist
  Borzoi:
    - Borzoi_L2_L2
    - minus_MAF
    - minus_TSS_dist
  GPN-MSA:
    - GPN-MSA_absLLR
    - minus_MAF
    - minus_TSS_dist
  phyloP-100v:
    - phyloP-100v
    - minus_MAF
    - minus_TSS_dist
  phastCons-100v:
    - phastCons-100v
    - minus_MAF
    - minus_TSS_dist
  phyloP-241m:
    - phyloP-241m
    - minus_MAF
    - minus_TSS_dist
#  Enformer_precomputed:
#    - Enformer_absDelta
#    - minus_MAF
#    - minus_TSS_dist
  Enformer_L2:
    - Enformer_L2
  Borzoi_L2:
    - Borzoi_L2
  Ensemble:
  - CADD_Annot
  - Borzoi_L2_L2
  - GPN-MSA_absLLR
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  Ensemble_precomputed:
  - GPN-MSA_absLLR
  - GPN-MSA_InnerProducts
  - Enformer_absDelta
  - phyloP-100v
  - phastCons-100v
  - phyloP-241m
  - minus_TSS_dist
  - minus_MAF
  - minus_MAF_popmax
  - CADD_Annot

dataset_eval_models:
  gonzalobenegas/siraj_gwas_highpip:
    - Baseline.RandomForest.chrom

    - Ensemble.RandomForest.chrom
    #- Ensemble.XGBoost.chrom

    - CADD.RandomForest.chrom
    - Enformer.RandomForest.chrom
    - Borzoi.RandomForest.chrom
    - GPN-MSA.RandomForest.chrom
    - phyloP-100v.RandomForest.chrom
    - phastCons-100v.RandomForest.chrom
    - phyloP-241m.RandomForest.chrom
  gonzalobenegas/siraj_eqtl_highpip:
    - Baseline.LogisticRegression.odd_even

    - Ensemble_precomputed.LogisticRegression.odd_even

    - GPN-MSA.LogisticRegression.odd_even
    - CADD.LogisticRegression.odd_even
    - Enformer_precomputed.LogisticRegression.odd_even
  gonzalobenegas/dsqtl:
    - Baseline.LogisticRegression.odd_even

    - Ensemble_precomputed.LogisticRegression.odd_even

    - GPN-MSA.LogisticRegression.odd_even
    - CADD.LogisticRegression.odd_even
    - Enformer_precomputed.LogisticRegression.odd_even
  gwas_gokcen_experiment1_Height:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
  gwas_gokcen_experiment1_BMD-HT:
    - Enformer_L2.LogisticRegression.chrom
    - Borzoi_L2.LogisticRegression.chrom
  #gwas_gokcen_merged_cre_matched:

baseline_features:
  gonzalobenegas/dsqtl:
    - Enformer_absDelta
  gonzalobenegas/siraj_gwas_highpip: []
  gonzalobenegas/siraj_eqtl_highpip:
    - Enformer_absDelta

gpn_msa:
  model_path: "songlab/gpn-msa-sapiens"
  msa_path: "/accounts/projects/yss/gbenegas/projects/gpn/analysis/human/results/msa/multiz100way/89/all.zarr"
  window_size: 128

gpn:
  model_path: /scratch/users/gbenegas/projects/gpn-animal-promoter/results/checkpoints/mlm/v2_all/512/512/512_17_512/checkpoint-100000
  window_size: 512